Update main.yml
Fallback to the Latest ChromeDriver:

If the script cannot find the exact matching ChromeDriver version for 128.0, it will now fallback to downloading the latest stable ChromeDriver.
Graceful Fallback:

The fallback mechanism prevents the workflow from failing if there's no exact ChromeDriver version for the detected Chrome version

Signed-off-by: Abhinav Tripathi <73254175+Abhinav1929@users.noreply.github.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,8 +30,12 @@ jobs:
         run: |
           CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+' | head -1)
           echo "Detected Chrome major version: $CHROME_VERSION"
-          # Fetch closest matching ChromeDriver version for the detected major Chrome version
-          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
+          # Try to get the matching ChromeDriver version for the detected major Chrome version
+          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION || echo "latest")
+          if [ "$CHROMEDRIVER_VERSION" == "latest" ]; then
+            echo "Could not find specific ChromeDriver version for $CHROME_VERSION. Downloading the latest ChromeDriver."
+            CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
+          fi
           echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION"
           curl -sS -o /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
           sudo unzip -q /tmp/chromedriver.zip -d /usr/local/bin/
